<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net48</TargetFramework><OutputType>Exe</OutputType><AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects><GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType></PropertyGroup>
  <ItemGroup><ProjectReference Include="../Data/A1IntegrationsAdmin.Data.csproj"/><Reference Include="System.Data"/></ItemGroup>
</Project>
